### ISSUE TITLE
Can't run vagrant on linux using AppImage

### ISSUE THREAD

**Issue by probonopd** [at15/code-i-read#6]
This must be a bug in the Vagrant AppImage. Please report it at https://github.com/hashicorp/vagrant/issues/.

Possibly related to https://github.com/hashicorp/vagrant/issues/9875?

**Comment by at15** [comment]
@probonopd  thx, opened the issue in https://github.com/hashicorp/vagrant/issues/10052

**Comment by at15** [comment]
fixed in upstream https://github.com/hashicorp/vagrant/pull/10078
